//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 04 10:25:41 CET 2007
//----------------------------------------------------

package org.processmining.importing.erlangnet.arcinscriptionparser;

/** CUP generated class containing symbol constants. */
public class sym {
	/* terminals */
	public static final int INTTYPE = 12;
	public static final int INT = 20;
	public static final int RPAREN = 3;
	public static final int VALUE = 19;
	public static final int RECEIVER = 15;
	public static final int STRINGTYPE = 13;
	public static final int LPAREN = 2;
	public static final int ID = 8;
	public static final int STRING = 21;
	public static final int COMMA = 16;
	public static final int PIDTYPE = 11;
	public static final int EOF = 0;
	public static final int SENDER = 7;
	public static final int SM = 17;
	public static final int SET = 6;
	public static final int PID = 4;
	public static final int error = 1;
	public static final int STRINGID = 18;
	public static final int BOOL = 22;
	public static final int GETPID = 10;
	public static final int BOOLTYPE = 14;
	public static final int ENV = 5;
	public static final int GET = 9;
}
