//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 21 23:35:38 CET 2007
//----------------------------------------------------

package org.processmining.importing.coloredcontrolflownet.arcinscriptionparser;

/** CUP generated class containing symbol constants. */
public class sym {
	/* terminals */
	public static final int INTTYPE = 14;
	public static final int RPAREN = 3;
	public static final int INT = 12;
	public static final int VALUE = 7;
	public static final int CONFS = 4;
	public static final int STRINGTYPE = 16;
	public static final int LBRACKET = 18;
	public static final int LPAREN = 2;
	public static final int ID = 11;
	public static final int RBRACKET = 19;
	public static final int STRING = 8;
	public static final int COMMA = 6;
	public static final int EOF = 0;
	public static final int PID = 5;
	public static final int error = 1;
	public static final int ASSIGN = 17;
	public static final int STRINGID = 9;
	public static final int BOOLTYPE = 15;
	public static final int BOOL = 10;
	public static final int GET = 13;
}
