/***********************************************************
 *      This software is part of the ProM package          *
 *             http://www.processmining.org/               *
 *                                                         *
 *            Copyright (c) 2003-2006 TU/e Eindhoven       *
 *                and is licensed under the                *
 *            Common Public License, Version 1.0           *
 *        by Eindhoven University of Technology            *
 *           Department of Information Systems             *
 *                 http://is.tm.tue.nl                     *
 *                                                         *
 **********************************************************/

package org.processmining.analysis.ltlchecker.parser;

/* Generated By:JJTree: Do not edit this line. ASTargList.java */

public class ASTargList extends SimpleNode {
	public ASTargList(int id) {
		super(id);
	}

	public ASTargList(LTLParser p, int id) {
		super(p, id);
	}
	
	public String asParseableString() {
		// this object actually doesn't contain any useful information that we could return here...
		return "";
	}
}
