/* Generated By:JJTree: Do not edit this line. ASTBiOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.processmining.analysis.ltlchecker.parser;

public
class ASTBiOp extends SimpleNode {
  public ASTBiOp(int id) {
    super(id);
  }

  public ASTBiOp(LTLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4743b68618cb0df84a11d6f712cce0b6 (do not edit this line) */
