/* Generated By:JJTree: Do not edit this line. ASTCompOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.processmining.analysis.ltlchecker.parser;

public
class ASTCompOp extends SimpleNode {
  public ASTCompOp(int id) {
    super(id);
  }

  public ASTCompOp(LTLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d558bdab4efe9ec1a9f87151a0021e46 (do not edit this line) */
