/* Generated By:JJTree: Do not edit this line. ASTdateAttributeDef.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.processmining.analysis.ltlchecker.parser;

public
class ASTdateAttributeDef extends SimpleNode {
  public ASTdateAttributeDef(int id) {
    super(id);
  }

  public ASTdateAttributeDef(LTLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=053424d724c6c99bf67d0832a50d3672 (do not edit this line) */
