/* Generated By:JJTree: Do not edit this line. ASTFormula.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.processmining.analysis.ltlchecker.parser;

public
class ASTFormula extends SimpleNode {
  public ASTFormula(int id) {
    super(id);
  }

  public ASTFormula(LTLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=de88ba419fcbdfbf0bca6dabb2d4ef3c (do not edit this line) */
