/***********************************************************
 *      This software is part of the ProM package          *
 *             http://www.processmining.org/               *
 *                                                         *
 *            Copyright (c) 2003-2006 TU/e Eindhoven       *
 *                and is licensed under the                *
 *            Common Public License, Version 1.0           *
 *        by Eindhoven University of Technology            *
 *           Department of Information Systems             *
 *                 http://is.tm.tue.nl                     *
 *                                                         *
 **********************************************************/

package org.processmining.analysis.ltlchecker.parser;

/* Generated By:JJTree: Do not edit this line. ASTFormulaCall.java */

import java.util.ArrayList;

public class ASTFormulaCall extends SimpleNode {

	/** List of values for the paramers of this formula.*/
	ArrayList values;

	public void setValues(ArrayList values) {
		this.values = values;
	}

	public ArrayList getValues() {
		return this.values;
	}

	public ASTFormulaCall(int id) {
		super(id);
	}

	public ASTFormulaCall(LTLParser p, int id) {
		super(p, id);
	}

    public String toString(boolean verbose) {
        return super.toString() + ": values=" + values;
    }
    
	public String asParseableString() {
		String result = "";
		
		for (Object o : values) {
			Attribute attr = (Attribute) o;
			
			if (result.length() > 0) { result += ", "; }
			if (attr.getKind() == Attribute.LITERAL) {
				result += attr.asParseableLiteralValue();
			} else {
				result += attr.asParseableValue();
			}
		}
		return getName() + "( " + result + " ) ";
	}
}
