/* Generated By:JJTree: Do not edit this line. ASTFinalFormula.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.processmining.analysis.ltlchecker.parser;

public
class ASTFinalFormula extends SimpleNode {
  public ASTFinalFormula(int id) {
    super(id);
  }

  public ASTFinalFormula(LTLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6e0d5c0bf3862832e8d6d6b77d1ab240 (do not edit this line) */
