/* Generated By:JJTree: Do not edit this line. ASTNumOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.processmining.analysis.ltlchecker.parser;

public
class ASTNumOp extends SimpleNode {
  public ASTNumOp(int id) {
    super(id);
  }

  public ASTNumOp(LTLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4a63771d1d15d90c5b103eca688f4abc (do not edit this line) */
