/* Generated By:JJTree: Do not edit this line. ASTnumberAttributeDef.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.processmining.analysis.ltlchecker.parser;

public
class ASTnumberAttributeDef extends SimpleNode {
  public ASTnumberAttributeDef(int id) {
    super(id);
  }

  public ASTnumberAttributeDef(LTLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=26c35f649922705fc87300b1fe8463d1 (do not edit this line) */
