/***********************************************************
 *      This software is part of the ProM package          *
 *             http://www.processmining.org/               *
 *                                                         *
 *            Copyright (c) 2003-2006 TU/e Eindhoven       *
 *                and is licensed under the                *
 *            Common Public License, Version 1.0           *
 *        by Eindhoven University of Technology            *
 *           Department of Information Systems             *
 *                 http://is.tm.tue.nl                     *
 *                                                         *
 **********************************************************/

package org.processmining.analysis.ltlchecker.parser;

/* Generated By:JJTree: Do not edit this line. ASTProposition.java */

public class ASTProposition extends SimpleNode {
	public ASTProposition(int id) {
		super(id);
	}

	public ASTProposition(LTLParser p, int id) {
		super(p, id);
	}

	public String asParseableString() {
		String result = "";
		
		if (children != null) {
			assert(children.length == 1);
			assert(children[0] != null);
			for (int i = 0; i < children.length; ++i) {
				SimpleNode n = (SimpleNode) children[i];
				if (n != null) {
					result += "  " + n.asParseableString() + "\n";
				}
			}
		}
		return result;
	}
}
