/* Generated By:JJTree: Do not edit this line. ASTstringAttributeDef.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.processmining.analysis.ltlchecker.parser;

public
class ASTstringAttributeDef extends SimpleNode {
  public ASTstringAttributeDef(int id) {
    super(id);
  }

  public ASTstringAttributeDef(LTLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5b5160e8f155d2a8c879157fe8f7c2e0 (do not edit this line) */
