/* Generated By:JJTree: Do not edit this line. ASTsetAttributeDef.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.processmining.analysis.ltlchecker.parser;

public
class ASTsetAttributeDef extends SimpleNode {
  public ASTsetAttributeDef(int id) {
    super(id);
  }

  public ASTsetAttributeDef(LTLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=969d21448989c04f8a02388acba6dc2d (do not edit this line) */
