/* Generated By:JJTree: Do not edit this line. ASTUnOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.processmining.analysis.ltlchecker.parser;

public
class ASTUnOp extends SimpleNode {
  public ASTUnOp(int id) {
    super(id);
  }

  public ASTUnOp(LTLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4eae6480f18168dfa5bd586a6365825a (do not edit this line) */
