/***********************************************************
 *      This software is part of the ProM package          *
 *             http://www.processmining.org/               *
 *                                                         *
 *            Copyright (c) 2003-2006 TU/e Eindhoven       *
 *                and is licensed under the                *
 *            Common Public License, Version 1.0           *
 *        by Eindhoven University of Technology            *
 *           Department of Information Systems             *
 *                 http://is.tm.tue.nl                     *
 *                                                         *
 **********************************************************/

package org.processmining.analysis.ltlchecker.parser;

/* Generated By:JJTree: Do not edit this line. ASTUnaryProposition.java */

public class ASTUnaryProposition extends SimpleNode {
	public ASTUnaryProposition(int id) {
		super(id);
	}

	public ASTUnaryProposition(LTLParser p, int id) {
		super(p, id);
	}

	public String asParseableString() {
		String result = "";
		
		switch (getType()) {
		case NOT: result = "!"; break;
		case ALWAYS: result = "[]"; break;
		case EVENTUALLY: result = "<>"; break;
		case NEXTTIME: result = "_O"; break;
		default:
			assert(false);
		};
		
		assert(children != null);
		assert(children.length == 1);
		assert(children[0] != null);
		
		result += " ( ";
		if (children != null) {
			for (int i = 0; i < children.length; ++i) {
				SimpleNode n = (SimpleNode) children[i];
				if (n != null) {
					result += n.asParseableString();
				}
			}
		}
		result += " ) ";
		return result;
	}
}
