/* Generated By:JavaCC: Do not edit this line. LTLParserTreeConstants.java Version 5.0 */
package org.processmining.analysis.ltlchecker.parser;

public interface LTLParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTATTRIBUTEDEFINITION = 1;
  public int JJTRENAMING = 2;
  public int JJTFORMULADEFINITION = 3;
  public int JJTARGLIST = 4;
  public int JJTARG = 5;
  public int JJTPROPOSITION = 6;
  public int JJTUNARYPROPOSITION = 7;
  public int JJTBINARYPROPOSITION = 8;
  public int JJTQUANTIFICATION = 9;
  public int JJTDUMMYVAR = 10;
  public int JJTCOMPARISON = 11;
  public int JJTFORMULACALL = 12;
  public int JJTVALUES = 13;
  public int JJTSTRINGLIST = 14;
  public int JJTCONCEPTSET = 15;
  public int JJTATTRIBUTE = 16;
  public int JJTVALUEATTRIBUTE = 17;
  public int JJTLITERAL = 18;
  public int JJTEXPR = 19;


  public String[] jjtNodeName = {
    "parse",
    "attributeDefinition",
    "renaming",
    "formulaDefinition",
    "argList",
    "arg",
    "Proposition",
    "UnaryProposition",
    "BinaryProposition",
    "Quantification",
    "DummyVar",
    "Comparison",
    "FormulaCall",
    "Values",
    "StringList",
    "conceptSet",
    "Attribute",
    "ValueAttribute",
    "Literal",
    "Expr",
  };
}
/* JavaCC - OriginalChecksum=1ae73d4b699d0fa6ba45450794be499b (do not edit this line) */
