/*
 * Copyright (c) 2007 Christian W. Guenther (christian@deckfour.org)
 * 
 * LICENSE:
 * 
 * This code is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
 * 
 * EXEMPTION:
 * 
 * License to link and use is also granted to open source programs which
 * are not licensed under the terms of the GPL, given that they satisfy one
 * or more of the following conditions:
 * 1) Explicit license is granted to the ProM and ProMimport programs for
 *    usage, linking, and derivative work.
 * 2) Carte blance license is granted to all programs developed at
 *    Eindhoven Technical University, The Netherlands, or under the
 *    umbrella of STW Technology Foundation, The Netherlands.
 * For further exemptions not covered by the above conditions, please
 * contact the author of this code.
 * 
 */
package org.processmining.analysis.traceclustering.algorithm;

import java.util.Iterator;

import javax.swing.JComponent;

import org.processmining.analysis.traceclustering.distance.DistanceMetric;
import org.processmining.analysis.traceclustering.model.Cluster;
import org.processmining.analysis.traceclustering.model.ClusterSet;
import org.processmining.analysis.traceclustering.model.InstancePoint;
import org.processmining.analysis.traceclustering.profile.AggregateProfile;

import cern.colt.matrix.DoubleFactory2D;
import cern.colt.matrix.DoubleMatrix2D;

/**
 * Base class for log / trace clustering algorithms in the trace clustering
 * framework.
 * 
 * @author Christian W. Guenther (christian@deckfour.org)
 */
public abstract class ClusteringAlgorithm {

	/**
	 * Name of the clustering algorithm
	 */
	protected String name;
	/**
	 * Description (1-2 sentences) of the clustering algorithm
	 */
	protected String description;
	/**
	 * Input for the clustering algorithm. The input is set by the framework as
	 * soon as it becomes available, before the algorithm gains visibility.
	 */
	protected ClusteringInput input;

	/**
	 * Constructor for the clustering algorithm
	 * 
	 * @param aName
	 *            Name of the algorithm
	 * @param aDescription
	 *            Short description
	 */
	protected ClusteringAlgorithm(String aName, String aDescription) {
		this.name = aName;
		this.description = aDescription;
	}

	/**
	 * Called by the framework to retrieve the user interface component of the
	 * clustering plugin. The user interface should display the results of
	 * clustering, as well as provide the necessary controls to influence the
	 * way traces are clustered (if applicable).
	 * <p>
	 * Clustering should be triggered from this user interface either explicitly
	 * (i.e., dedicated button) or implicitly (i.e., when control values are
	 * modified).
	 * <p>
	 * At the time the user interface is requested by the framework through
	 * calling this method, the algorithm will have the clustering input set by
	 * the framework, so that clustering may start immediately. A result cluster
	 * set will only be requested by the framework after calling this method.
	 * Thus, it is also a good place to perform initialization of your
	 * algorithm.
	 * 
	 * @return The user interface of the clustering plugin
	 */
	public abstract JComponent getUI();

	/**
	 * The framework calls this method to retrieve the result of clustering,
	 * i.e. a set of clusters, from the plugin. This is used for making these
	 * results available to the rest of the framework.
	 * 
	 * @return the set of clusters generated by this algorithm
	 */
	public abstract ClusterSet getClusters();

	/**
	 * The framework calls this method to provide the clustering algorithm with
	 * the input (log, profile, distance metric) that may be used to generate
	 * clusters of the provided log.
	 * 
	 * @param anInput
	 *            clustering input, providing references to the log, profiles,
	 *            and distance metric.
	 */
	public void setInput(ClusteringInput anInput) {
		input = anInput;
	}

	/**
	 * Returns the name of the clustering algorithm
	 * 
	 * @return
	 */
	public String getName() {
		return name;
	}

	/**
	 * Returns a description (1-2 sentences) about the algorithm
	 * 
	 * @return
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Returns the name of this algorithm
	 * 
	 * @return
	 */
	public String toString() {
		return name;
	}

	/**
	 * calculate inter-cluster distance
	 * 
	 * @return
	 */
	protected DoubleMatrix2D calculateInterClusterDistance(ClusterSet clusters) {
		InstancePoint[] instancePoints;
		instancePoints = new InstancePoint[clusters.size()];
		AggregateProfile agProfiles = clusters.getAGProfiles();
		DistanceMetric distanceMeasures = input.getDistanceMetric();
		for (int i = 0; i < clusters.size(); i++) {
			instancePoints[i] = new InstancePoint();
			Cluster tempCluster = (Cluster) clusters.getClusters().get(i);
			if (tempCluster.size() == 0)
				continue;
			instancePoints[i] = null;
			instancePoints[i] = new InstancePoint();
			Iterator itr = tempCluster.getTraceIndices().iterator();
			while (itr.hasNext()) {
				int index = (Integer) itr.next();
				InstancePoint iPoint = agProfiles.getPoint(index);
				Iterator itr2 = iPoint.getItemKeys().iterator();
				while (itr2.hasNext()) {
					String key = (String) itr2.next();
					if (instancePoints[i].getItemKeys().contains(key))
						instancePoints[i].set(key, instancePoints[i].get(key)
								+ iPoint.get(key));
					else
						instancePoints[i].set(key, iPoint.get(key));
				}
			}
			itr = instancePoints[i].getItemKeys().iterator();
			while (itr.hasNext()) {
				String key = (String) itr.next();
				instancePoints[i].set(key, instancePoints[i].get(key)
						/ tempCluster.size());
			}
		}

		DoubleMatrix2D D = DoubleFactory2D.dense.make(instancePoints.length,
				instancePoints.length, 0);
		for (int i = 0; i < instancePoints.length - 1; i++) {
			for (int j = i + 1; j < instancePoints.length; j++) {
				double temp = distanceMeasures.getDistance(instancePoints[i],
						instancePoints[j]);
				D.set(i, j, temp);
				D.set(j, i, temp);
			}
		}
		System.out.println("inter distance");
		for (int i = 0; i < instancePoints.length; i++) {
			for (int j = 0; j < instancePoints.length; j++) {
				System.out.print(D.get(i, j) + ", ");
			}
			System.out.println();
		}
		return D;
	}

	/**
	 * calculate intra-cluster distance
	 * 
	 * @return
	 */
	protected double[] calculateIntraClusterDistance(ClusterSet clusters) {
		double[] centers = new double[clusters.size()];
		AggregateProfile agProfiles = clusters.getAGProfiles();
		DistanceMetric distanceMeasures = input.getDistanceMetric();

		for (int i = 0; i < clusters.size(); i++) {
			Cluster tempCluster = (Cluster) clusters.getClusters().get(i);
			if (tempCluster.size() == 0)
				continue;
			double temp = 0.0;
			for (int j = 0; j < tempCluster.getTraceIndices().size() - 1; j++) {
				InstancePoint iPoint = agProfiles.getPoint(tempCluster
						.getTraceIndices().get(j));
				for (int k = j + 1; k < tempCluster.getTraceIndices().size(); k++) {
					InstancePoint iPoint2 = agProfiles.getPoint(tempCluster
							.getTraceIndices().get(k));
					temp += distanceMeasures.getDistance(iPoint, iPoint2);
				}
			}
			centers[i] = temp / (clusters.size() * (clusters.size() - 1) / 2);
			System.out.println("cluster " + i + ": " + centers[i]);
		}
		return centers;
	}

}
