/* Generated By:JavaCC: Do not edit this line. TpnParserConstants.java */
package org.processmining.importing.tpn;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TpnParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NAME = 9;
  /** RegularExpression Id. */
  int NUMBER = 10;
  /** RegularExpression Id. */
  int EXPONENT = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"place\"",
    "\"trans\"",
    "\"init\"",
    "\"inf\"",
    "\"in\"",
    "\"out\"",
    "\"~\"",
    "\";\"",
    "<NAME>",
    "<NUMBER>",
    "<EXPONENT>",
    "\" \"",
    "<token of kind 13>",
    "<token of kind 14>",
  };

}
